name: Go Test

on:
  push:
    branches: [main]
    paths:
      - "pg_stream/**"
  pull_request:
    branches: [main]
    paths:
      - "pg_stream/**"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pg_stream

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
